site_name: eCoolGe`s Grind75
site_url: https://ecoolge.github.io/grind75/
site_description: My digital garden powered by Obsidian and MkDocs
dev_addr: 127.0.0.1:8001
site_author: eCoolGe
repo_url: https://github.com/eCoolGe/grind75
repo_name: eCoolGe/grind75

docs_dir: docs

plugins:
  - search
  - awesome-nav  # Автонавигация
  - tags:           # Поддержка тегов
      listings_map:
        difficulties-tags:
          include:
            - Easy
            - Medium
            - Hard
        categories-tags:
          include:
            - Array
            - Binary Search
            - Binary Search Tree
            - Binary Tree
            - Bit Manipulation
            - Breadth-First Search
            - Counting
            - Depth-First Search
            - Design
            - Divide and Conquer
            - Dynamic Programming
            - Greedy
            - Hash Table
            - Interactive
            - Linked List
            - Math
            - Matrix
            - Memoization
            - Queue
            - Recursion
            - Simulation
            - Sliding Window
            - Sorting
            - Stack
            - String
            - Tree
            - Two Pointers
            - Union Find
  - ezlinks        # Улучшенные внутренние ссылки
  - git-revision-date-localized  # Даты изменений
  - minify         # Оптимизация HTML/CSS/JS
  - obsidian-support
  - callouts
  - git-authors
#  - with-pdf       # Генерация PDF (опционально)
#  - mkdocs-obsidian:  # Обработка Obsidian-синтаксиса
#      wikilinks: true
#      highlight: true
#      comments: true
#      dataview: false  # (пока нет полной поддержки)

theme:
  name: material
  custom_dir: docs/overrides
  language: ru
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.footer
    - search.highlight
    - search.suggest
    - search.share
    - content.tabs.link
    - content.code.annotate
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Auto
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Dark mode

  font:
    text: Roboto
    code: Fira Code

markdown_extensions:
  - admonition
  - nl2br
  - codehilite
  - footnotes
  - meta
  - attr_list  # Для кастомных атрибутов
  - toc:
      permalink: true
  - pymdownx.arithmatex:  # Математика
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.superfences
  - pymdownx.details  # Сворачиваемые блоки
  - pymdownx.emoji:   # Emoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tilde # Зачеркнутый текст
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:  # Чекбоксы
      custom_checkbox: true

#extra_css:
#  - css/obsidian.css  # Кастомные стили (если нужны)

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js  # MathJax

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/eCoolGe
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ecoolge/

#exclude_docs: |
#  /.obsidian/
#  obsidian/templates/